// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTmAxHPjtCce3AHUBKhMKVAJKcoeqtYdg',
    appId: '1:23125219517:web:7b0c765fa9faea94f37fd4',
    messagingSenderId: '23125219517',
    projectId: 'api-img-f0f54',
    authDomain: 'api-img-f0f54.firebaseapp.com',
    storageBucket: 'api-img-f0f54.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVI91pnPu4ZEcp1Gag4r0rIHJKOYd-eLc',
    appId: '1:23125219517:android:9be31942020349b9f37fd4',
    messagingSenderId: '23125219517',
    projectId: 'api-img-f0f54',
    storageBucket: 'api-img-f0f54.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOYoz7tb8APFQV2_DEdymo3V1FqncQqK8',
    appId: '1:23125219517:ios:9a84dfceaf70cb2ef37fd4',
    messagingSenderId: '23125219517',
    projectId: 'api-img-f0f54',
    storageBucket: 'api-img-f0f54.appspot.com',
    iosBundleId: 'com.example.unsplis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOYoz7tb8APFQV2_DEdymo3V1FqncQqK8',
    appId: '1:23125219517:ios:9a84dfceaf70cb2ef37fd4',
    messagingSenderId: '23125219517',
    projectId: 'api-img-f0f54',
    storageBucket: 'api-img-f0f54.appspot.com',
    iosBundleId: 'com.example.unsplis',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTmAxHPjtCce3AHUBKhMKVAJKcoeqtYdg',
    appId: '1:23125219517:web:9f302170db2b8f10f37fd4',
    messagingSenderId: '23125219517',
    projectId: 'api-img-f0f54',
    authDomain: 'api-img-f0f54.firebaseapp.com',
    storageBucket: 'api-img-f0f54.appspot.com',
  );

}